-- SCRIPT: SkillShift.AI - Banco de Dados (Oracle)
-- Autor: Equipe SkillShift
-- Disciplina: Building Relational Database - FIAP

-- DDL
CREATE TABLE t_skillshift_usuario (
    id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR2(100) NOT NULL,
    email           VARCHAR2(120) NOT NULL,
    senha_hash      VARCHAR2(255) NOT NULL,
    idade           NUMBER(3) NOT NULL,
    escolaridade    VARCHAR2(50) NOT NULL,
    area_atual      VARCHAR2(50) NOT NULL,
    nivel_risco     NUMBER(5,2) DEFAULT 0,
    tipo_perfil     VARCHAR2(20) NOT NULL,
    criado_em       DATE DEFAULT SYSDATE,
    CONSTRAINT pk_t_skillshift_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_t_skillshift_usuario_email UNIQUE (email),
    CONSTRAINT ck_t_skillshift_usuario_tipo CHECK (tipo_perfil IN ('USER','ADMIN','EMPRESA')),
    CONSTRAINT ck_t_skillshift_usuario_risco CHECK (nivel_risco BETWEEN 0 AND 100),
    CONSTRAINT ck_t_skillshift_usuario_idade CHECK (idade BETWEEN 16 AND 80)
);

CREATE TABLE t_skillshift_curso (
    id_curso        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR2(120) NOT NULL,
    categoria       VARCHAR2(50) NOT NULL,
    duracao_horas   NUMBER(4),
    plataforma      VARCHAR2(120),
    nivel           VARCHAR2(20),
    ativo           CHAR(1) DEFAULT 'S',
    CONSTRAINT pk_t_skillshift_curso PRIMARY KEY (id_curso),
    CONSTRAINT ck_t_skillshift_curso_nivel CHECK (nivel IN ('INICIAL','INTERMEDIARIO','AVANCADO')),
    CONSTRAINT ck_t_skillshift_curso_ativo CHECK (ativo IN ('S','N')),
    CONSTRAINT ck_t_skillshift_curso_duracao CHECK (duracao_horas IS NULL OR duracao_horas > 0)
);

CREATE TABLE t_skillshift_empresa (
    id_empresa      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR2(120) NOT NULL,
    setor           VARCHAR2(80),
    tamanho         VARCHAR2(50),
    cnpj            VARCHAR2(18),
    CONSTRAINT pk_t_skillshift_empresa PRIMARY KEY (id_empresa),
    CONSTRAINT ck_t_skillshift_empresa_tamanho CHECK (tamanho IN ('PEQUENA','MEDIA','GRANDE')),
    CONSTRAINT uk_t_skillshift_empresa_cnpj UNIQUE (cnpj)
);

CREATE TABLE t_skillshift_usuario_empresa (
    id_usuario      NUMBER NOT NULL,
    id_empresa      NUMBER NOT NULL,
    cargo           VARCHAR2(80),
    data_inicio     DATE,
    CONSTRAINT pk_t_skillshift_usuario_empresa PRIMARY KEY (id_usuario, id_empresa),
    CONSTRAINT fk_t_skillshift_usuario_empresa_usuario FOREIGN KEY (id_usuario) REFERENCES t_skillshift_usuario (id_usuario),
    CONSTRAINT fk_t_skillshift_usuario_empresa_empresa FOREIGN KEY (id_empresa) REFERENCES t_skillshift_empresa (id_empresa)
);

CREATE TABLE t_skillshift_recomendacao (
    id_recomendacao   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario        NUMBER NOT NULL,
    id_curso          NUMBER NOT NULL,
    score             NUMBER(5,2) NOT NULL,
    fonte             VARCHAR2(30) NOT NULL,
    status            VARCHAR2(20) DEFAULT 'PENDENTE',
    data_recomendacao DATE DEFAULT SYSDATE,
    cluster_id        NUMBER,
    payload_ia        CLOB,
    CONSTRAINT pk_t_skillshift_recomendacao PRIMARY KEY (id_recomendacao),
    CONSTRAINT fk_t_skillshift_rec_usuario FOREIGN KEY (id_usuario) REFERENCES t_skillshift_usuario (id_usuario),
    CONSTRAINT fk_t_skillshift_rec_curso FOREIGN KEY (id_curso) REFERENCES t_skillshift_curso (id_curso),
    CONSTRAINT ck_t_skillshift_rec_fonte CHECK (fonte IN ('IA','EMPRESA','MANUAL')),
    CONSTRAINT ck_t_skillshift_rec_status CHECK (status IN ('PENDENTE','EM_ANDAMENTO','CONCLUIDA')),
    CONSTRAINT ck_t_skillshift_rec_score CHECK (score BETWEEN 0 AND 100)
);

CREATE TABLE t_skillshift_curso_alias (
    id_alias   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_curso   NUMBER NOT NULL,
    termo      VARCHAR2(150) NOT NULL,
    CONSTRAINT pk_t_skillshift_curso_alias PRIMARY KEY (id_alias),
    CONSTRAINT uq_t_skillshift_curso_alias UNIQUE (id_curso, termo),
    CONSTRAINT fk_t_skillshift_curso_alias FOREIGN KEY (id_curso) REFERENCES t_skillshift_curso (id_curso)
);

CREATE TABLE t_skillshift_recomendacao_ia_log (
    id_log            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario        NUMBER NOT NULL,
    cluster_id        NUMBER,
    payload_envio     CLOB,
    payload_retorno   CLOB,
    status            VARCHAR2(20),
    erro              VARCHAR2(400),
    criado_em         DATE DEFAULT SYSDATE,
    CONSTRAINT pk_t_skillshift_recomendacao_log PRIMARY KEY (id_log),
    CONSTRAINT fk_t_skillshift_recomendacao_log_usuario FOREIGN KEY (id_usuario) REFERENCES t_skillshift_usuario (id_usuario)
);
