-- SCRIPT: SkillShift.AI - Banco de Dados (Oracle)
-- Autor: Equipe SkillShift
-- Disciplina: Building Relational Database - FIAP

-- DROP
DROP TABLE TB_RECOMENDACAO_IA_LOG CASCADE CONSTRAINTS;
DROP TABLE TB_CURSO_ALIAS CASCADE CONSTRAINTS;
DROP TABLE TB_RECOMENDACAO CASCADE CONSTRAINTS;
DROP TABLE TB_USUARIO_EMPRESA CASCADE CONSTRAINTS;
DROP TABLE TB_CURSO CASCADE CONSTRAINTS;
DROP TABLE TB_EMPRESA CASCADE CONSTRAINTS;
DROP TABLE TB_USUARIO CASCADE CONSTRAINTS;
